spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:forum;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;MODE=MySQL;
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
#    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  h2:
    console:
      path: /forum-console